### ISSUE TITLE
Catch invalid/used verification token response

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#105]
The verification page now has a single error page. This can be expanded to include an expired / already used token message.

**Comment by TimvdLippe** [comment]
What is the errorcode of the api? Based on that I could alter the message.

**Comment by skamoen** [comment]
`{"status":"401","timestamp":"2016-03-01T16:17:33.174","message":"Token is expired or has been already used.","object":null}`

While a non-existing token retuns
`{"status":"404","timestamp":"2016-03-01T16:18:14.173","message":"could not find token 'ab5d2d1a-e730-4b9e-aac3-b7d2257'.","object":null}`

**Comment by TimvdLippe** [comment]
Waiting for #97 to use the new card element, to prevent duplication and copy-pasta
