### ISSUE TITLE
Fix poor English

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#106]
kutsjaars. Learn2English

For example 

>Hmm, there seemed to have gone something wrong with the verification of your account.
        Please <a href="mailto:lancie@ch.tudelft.nl">send us an email</a> containing your email-adres and username.
        We will then check what went wrong.

That's not proper English.

**Comment by TimvdLippe** [comment]
ping @bvanderdrift Seems an easy to fix issue.

**Comment by bvanderdrift** [comment]
Oops, missed this. Thanks for fixing.
