### ISSUE TITLE
Set up CI to check for errors

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#122]
We need a CI to check if:
1. The build (`gulp`) succeeds
2. Jshint (`gulp jshint`) does not report any issues (requires quite some fixes though)

**Comment by skamoen** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Using-Gulp

**Comment by TimvdLippe** [comment]
in `gulpfile.js` `require('glob')` should be `require('glob-all')`
