### ISSUE TITLE
Registering Page always gives "Username and/or email are already taken." upon a error.

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#143]
I vote for this as a very important issue. We've had multiple people contacting us that their username has been taken whilst it was probably their internet connection failing. There was once a guy that even tried to reset his password after he got that message since this led him to believe he already had a registered account.

**Comment by skamoen** [comment]
We handle this for login, but not for registering. Should be something similar to the login code
```
      onFailedLogin: function(event, request) {
        this.loginError = true;
        if (request.request.status === 401) {
          this.loginErrorMessage = 'Bad credentials.';
        } else {
          this.loginErrorMessage = 'Server failed processing the request.';
        }
      },
```
