### ISSUE TITLE
Self organized tournaments on front page

### ISSUE THREAD

**Issue by drennings** [AreaFiftyLAN/lancie-frontend#144]
Add the self organized tournaments to the front page similar to the display of the official tournaments as done in the image below, but probably in a smaller fashion (smaller images e.g. 5 or 6 on one line).

![image](https://cloud.githubusercontent.com/assets/7381475/13668122/e22fc306-e6ba-11e5-9cbb-a79e712b5677.png)

**Comment by drennings** [comment]
At this moment, we are sure to have:
-A minecraft tournament
-A poker tournament

We are still discussing about:
-A melee tournament

**Comment by TimvdLippe** [comment]
For this to happen you need to:

1. Add a new .json similar to https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/scripts/activity.json
* Update activities to adjust width: https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/elements/lancie-activity/lancie-activities.html#L25-L32
* Add the `<lancie-activities json="location_of_new_json.json"><lancie-activities>` on the homepage: https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/elements/lancie-home-page/lancie-home-page.html#L109

**Comment by skamoen** [comment]
Fixed
