### ISSUE TITLE
Enable header menu on mobile again

### ISSUE THREAD

**Issue by mgajanssen** [AreaFiftyLAN/lancie-frontend#159]
Now that the mobile layout is correct, we can re-enable the menu in the header!

**Comment by TimvdLippe** [comment]
We do need to solve the positioning problem though, any thoughts? We could maybe horizontally align them in the center beneath the logo.

**Comment by martijn9612** [comment]
We could have some kind of button in the header that opens and collapses a small menu containing these links. This way it is not in the way of the site and still easily accessible.
