### ISSUE TITLE
Missing ajax headers when using auto-login

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-frontend#16]

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue on current master. Can you provide reproduction steps?

**Comment by svenpopping** [comment]
Go to ticket -> Login -> Add ticket and it shows up in the cart. Then close the tab and repeat the process, but then you get a bad request on the add ticket call.

**Comment by skamoen** [comment]
That might be another issue. Users can only have one open Order. I corrected this in the ticket-availability-overview branch, but on master you'll get an ImmutableOrderException.

```
        if (order.getStatus().equals(OrderStatus.CREATING)) {

        } else {
            throw new ImmutableOrderException(orderId);
        }
```

**Comment by TimvdLippe** [comment]
![image](https://cloud.githubusercontent.com/assets/5948271/12377808/6996ccbe-bd2a-11e5-9cb5-d17bdc4ad6e8.png)

**Comment by TimvdLippe** [comment]
The request was failing due to another issue. This has subsequently been fixed, so closing this issue.
