### ISSUE TITLE
Add SPAM Logo to sponsors

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#163]
SPAM should go under a new header "Sponsors"

Logo:
![spam_logo](https://cloud.githubusercontent.com/assets/6398452/13967495/b6904a60-f077-11e5-806e-0b3d057c2a22.png)

**Comment by bvanderdrift** [comment]
This is a high priority item. Can @Icety @TimvdLippe @martijn9612 @skamoen maybe give me an estimate on how soon this issue can be solved?

**Comment by skamoen** [comment]
The black background makes me very unhappy. Is there an alternative?

![image](https://cloud.githubusercontent.com/assets/3198784/14123178/997cc68c-f5ff-11e5-8106-ad5b187c0cf8.png)

**Comment by bvanderdrift** [comment]
Can you remember how you placed the logo last year?

**Comment by skamoen** [comment]
We didn't

**Comment by svenpopping** [comment]
![img_2016-03-29 23 21 45](https://cloud.githubusercontent.com/assets/5946485/14124301/10db9974-f605-11e5-9f80-facc7f1da35b.jpg)

This was the original idea!

**Comment by bvanderdrift** [comment]
Thanks @svenpopping. I'll look into finding a substitute logo.

**Comment by bvanderdrift** [comment]
Is this a good enough resolution? Has a transparent background making it perfect for the design @svenpopping posted.

http://ruz3-gaming.be/img/sps/ed2d0969529de2d6c34d0bdc04e6b93a.png
