### ISSUE TITLE
Change all urls to the same format

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#174]
Some urls currently use upper case letters. Some others are all lowercase. This needs to be fixed through the entire project. Also remember to change this in de links we send in the emails and so on.

**Comment by TimvdLippe** [comment]
The URL scheme needs a thorough revamp together with the API. This is probably related to #299 and #294

**Comment by martijnjanssen** [comment]
This is true, but for #294 we only want to display text and not have any js functionality in the page. To me it would only add unneeded complexity and mixed responsibilities.

**Comment by TimvdLippe** [comment]
Oh this one we still need to do? Big issue which needs te be fixed before ticket sale

**Comment by skamoen** [comment]
Looking at https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-content.html, seems like this is fixed. Should be updated in the api though

**Comment by martijnjanssen** [comment]
This was fixed in #362.
