### ISSUE TITLE
[Seatmap] Overview & Search

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#176]
Next to reservation, people also need to be able to find eachother (and their own seat). This requires some form of search. Ideally a single box where you can search for Displayname, Teamname, First and Last name.

Acceptable, and possibly easier solution: A box containing different input fields for each of these search terms. API already contains most of the required functionality, or should be very easy to extend.

**Comment by bvanderdrift** [comment]
Fixed in #263

**Comment by bvanderdrift** [comment]
Although, only searchable by displayname right now. We've decided First and Last name leaks too much personal information. Searching by teamname is not implemented right now

**Comment by martijn9612** [comment]
Searching on teamname adds too much overhead in my opinion. You need to retrieve all teams and couple them to the user or send a request for each users' team.

**Comment by skamoen** [comment]
No you dont: https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/controller/SeatRestController.java#L209

**Comment by martijn9612** [comment]
Yes you do, you just linked to a route that requires you to know the id of the team. So for this to work, you need to retrieve all the seats of all teams to be able to search for team you are looking for.
