### ISSUE TITLE
Fix Polylint errors

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#178]
We haven't been running Polylint. This means nearly every file contains a number of errors which should be fixed. Combine this with enabling polylint on Travis

**Comment by TimvdLippe** [comment]
We should investigate whether some errors are intended to be fixed. Also if we enable this on Travis, all issues should be fixed or all our builds will fail. Preferably also in a different subtask, which requires a new `gulp` task.

**Comment by TimvdLippe** [comment]
We do not have `polylint` installed, but we have `jshint` right now

**Comment by FrancisBehnen** [comment]
If you want support within VS Code: Ctrl + P -> `ext install jshint`

**Comment by martijnjanssen** [comment]
Is this PR actually resolved or do we not want to close this yet? We are currently not checking or failing on linting errors since it is run before the build and only gives warnings.

**Comment by TimvdLippe** [comment]
We could enable it to fail on Travis, but they are small warnings for now. The linter does catch errors though. If you want to enable it on Travis, I am okay with that
