### ISSUE TITLE
Fix neon-animations

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-frontend#187]
The default neon-animations do not work
![screen shot 2016-05-06 at 00 12 08](https://cloud.githubusercontent.com/assets/5946485/15058884/3a57d8ee-131f-11e6-9912-0127f8ad4c48.png)

**Comment by skamoen** [comment]
I'm not seeing this anymore. Is this fixed?

**Comment by svenpopping** [comment]
It is fixed now 👍
