### ISSUE TITLE
Place Text on the current header with event information

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#19]
Example:

![lance-header-example](https://cloud.githubusercontent.com/assets/6398452/12676818/1a4b2e92-c695-11e5-8c90-7c44a693ff79.png)

**Comment by bvanderdrift** [comment]
Preferably the subtext "Early Bird Tickets available soon!"

**Comment by skamoen** [comment]
Fixed in #50
