### ISSUE TITLE
Selected tab is incorrect after refresh

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#193]
### Steps to reproduce
1. Open the website
* Go to My area
* Refresh the page
* Observe that the selected `paper-tab` is "Home" instead of "My Area"

**Comment by martijn9612** [comment]
This actually happens on every page. It just resets to the `Home` tab.

**Comment by TimvdLippe** [comment]
It appears that the `selected` property of `paper-tabs` is not data-bound to the actual page (see https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/elements/lancie-header/lancie-header.html#L35)

**Comment by martijn9612** [comment]
I have tried some values but could not figure out what it should be unfortunately. I will look into this later.
