### ISSUE TITLE
Sponsor align on Safari

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#194]
It behaves like mobile on Safari

![wisvch slack com](https://cloud.githubusercontent.com/assets/3198784/15100382/51916e3c-1570-11e6-81b3-1011eb8f5333.png)

**Comment by svenpopping** [comment]
Great image :)

**Comment by skamoen** [comment]
![screen shot 2016-05-08 at 22 53 41](https://cloud.githubusercontent.com/assets/3198784/15113369/28ba8186-15f4-11e6-9456-88694e015d8a.png)

Take two
