### ISSUE TITLE
Add Topicus as Sponsor of Minecraft Tournament

### ISSUE THREAD

**Issue by drennings** [AreaFiftyLAN/lancie-frontend#196]
Put Topicus as Sponsor on the Minecraft tournament (name and logo) including the prices:

1. Fitbit Flex
2. Philips Speaker (SBA3011, SoundShooter) + Squid Mini Powerbank (http://www.xoopar.com/SQUIDMINI) 
3. Monopoly Deventer Editie

Not sure if you also want to add the price of the prizes ("ter waarde van")?

**Comment by drennings** [comment]
Not sure if we also (want to) have space to add pictures of the prizes?

**Comment by bvanderdrift** [comment]
Excuse me.

**Comment by bvanderdrift** [comment]
Solved by #203
