### ISSUE TITLE
"Server is unable to process the request" on login

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#198]
We're getting reports of people experiencing the `server is unable to process the request` message upon login. Some of the team experienced the same, and a refresh fixes it. Hard to reproduce, but it's clearly an issue. 

Possibly something cache related. 

Workaround is changing the error message to suggest a refresh, but this has to be investigated somehow. 

Initially assigning @TimvdLippe

**Comment by skamoen** [comment]
Managed to reproduce while network monitoring was turned on:

`{"timestamp":1462994736169,"status":403,"error":"Forbidden","message":"Invalid CSRF Token 'b882b736-46ac-47af-8ffa-5d8e40c7dda2' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.","path":"/api/v1/login"}`

Seems like the CSRF token is stored. This should be wiped more often, but not sure when.

**Comment by TimvdLippe** [comment]
Should be fixed now with tokenbased login.
