### ISSUE TITLE
Add Startselect as sponsor on the site

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#211]
Website: https://startselect.com
Logo:

![logo start select rgb_dtp](https://cloud.githubusercontent.com/assets/6398452/15409825/d8980734-1e16-11e6-9b46-7adfd776d3de.png)

**Comment by bvanderdrift** [comment]
I missed #207, but this logo is required instead of the logo in that issue.

**Comment by martijn9612** [comment]
This logo is way better, way more pixels of awesomeness!
