### ISSUE TITLE
Mobile timetable should be scrollable on mobile instead of scale

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#222]
![screenshot_2016-05-22-13-32-02](https://cloud.githubusercontent.com/assets/6398452/15453771/db3ae224-2021-11e6-9884-4ed6bcbc0f4c.png)

**Comment by martijnjanssen** [comment]
An easy fix with the use of #494

**Comment by martijnjanssen** [comment]
This was merged in #495!
