### ISSUE TITLE
It shouldn't be possible to try to reserve a seat when not having a ticket.

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#224]
Dialog Box upon selecting seat should notify user they don't own a ticket and thus can't reserve a seat.

![image](https://cloud.githubusercontent.com/assets/6398452/15454471/9cf9f64a-2039-11e6-8aaf-a68177350616.png)

**Comment by skamoen** [comment]
Already fixed in #221
