### ISSUE TITLE
Switch to Polymer App Toolbox

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#225]
A5L 2017 should switch to the new Polymer App Toolbox. This includes new tooling that replaces most gulp stuff, lazy loading, app-route. 

https://www.polymer-project.org/1.0/toolbox/

This will resolve a lot of open issues, so this switch should be made as soon as possible after the 2016 event.

**Comment by TimvdLippe** [comment]
Superseded by #283. Sorry I missed this one
