### ISSUE TITLE
Timed Messages in Yellow Bar

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#227]
It should be possible to schedule messages in the Yellow bar. Think about

* A timer for a deadline for a give-away
* A timer for when the event starts
* A link to a stream once the event is busy
* A big thank you after the event
* More

**Comment by martijn9612** [comment]
This should be solved by the API. The API should return the banner content. The frontend only has to display said content. This is described in #215 .
