### ISSUE TITLE
Sponsors vertically stacked on Safari

### ISSUE THREAD

**Issue by karimosman** [AreaFiftyLAN/lancie-frontend#228]
Browser Details:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

<img width="938" alt="schermafbeelding 2016-05-23 om 11 57 21" src="https://cloud.githubusercontent.com/assets/5946519/15467203/9c3934ce-20dd-11e6-83bb-6a2edb03726e.png">

**Comment by bvanderdrift** [comment]
Duplicate in #194
