### ISSUE TITLE
Enable https for the website

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#23]
Enabling https offers:

1. Security (who doesn't like security)
2. Service-worker usage (faster pages == :+1: :+1: )
3. Unlocks HTTP2
4. Higher ranking in search engines (positive side-effect)

Free certificates with Let's Encrypt (https://letsencrypt.org/howitworks/).
If the server runs NGinx: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04
For Apache: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

Probably need to discuss with the sys admins of what our possibilities are.

**Comment by skamoen** [comment]
We already had this last year (it's on the site currently online) including certificates and such. We'll get to this when launching the new version.
