### ISSUE TITLE
Cannot invite player with spaces in their username

### ISSUE THREAD

**Issue by jamy015** [AreaFiftyLAN/lancie-frontend#250]
I tried to invite a player to my team who had spaces in his username, but this led to an error telling me that he was not found. After he changed his username to one without any spaces, I was able to invite him without problems.

**Comment by skamoen** [comment]
You've probably been inviting people based on their displayName, which is something different from the username. The changed displayname was probably equal to his username, making it work. 

The difference between usernames and displaynames is obviously unclear, which is something we'll look into for future versions. Glad it all worked out in the end :)
