### ISSUE TITLE
Replace colors with material design equivalents

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#264]
https://github.com/PolymerElements/paper-styles/blob/master/color.html

**Comment by skamoen** [comment]
You want to change the colorscheme just to adhere to material design? Doesn't sound like a good idea to me.

**Comment by martijn9612** [comment]
I don't want to adjust the color scheme of the entire website, but we are using material design colors for some windows. Would be more logical to change these to the variable types. An example is the error message in login.

**Comment by skamoen** [comment]
In that case, specify those things so they can be replaced. Now it's completely unclear what has to be done to resolve this issue.

**Comment by martijn9612** [comment]
That is correct. Actually, every color can be replaced, we can define our own variables and have all the colors in one file. So our own colors file would suffice, with an import of the polymer colors.
