### ISSUE TITLE
Implement form validation

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#293]
The validation of our contact form is done in a more elegant way, using the incorporated properties in `paper-input`. This allows for a cleaner UI and error messages coupled to the incorrect field. This should be implemented across the several pages that still use `paper-material` for error messages. More global messages are still allowed to reside in the `paper-material` elements.

**Comment by martijnjanssen** [comment]
This can be done even better with #363. The lancie-form element handles validation and requests with data.

**Comment by skamoen** [comment]
This is replace at most places. Open specific issue when it's still spotted
