### ISSUE TITLE
Remove unneeded homepage complexity

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#296]
The ajax call to the markdown file for organization of your own events is not needed. This could simply be done by putting the location of the file in there.

Another thing that can be removed are the properties in the javascript, those are not used at all.

**Comment by TimvdLippe** [comment]
If I recall correctly, the markdown url was specified on the API and required for the Belgium LAN event as they had a different file. I am fine with removing them though 😄

**Comment by martijnjanssen** [comment]
This is fixed in the api right now, all tournament data is not retrieved from the api!
