### ISSUE TITLE
Replace lancie-dialog

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#297]
`lancie-dialog` is a big mess right now. It contains weirdly styled property overrides and is not build in a proper polymer way. This should be changed. We should also only provide the bare minimum properties, setting the opening animation every time has no need.

**Comment by FrancisBehnen** [comment]
Are there any extra requests for this, or should it just be the same element but with cleaner code?

**Comment by TimvdLippe** [comment]
Cleaner code and also more performant. @martijnjanssen observed slight CPU increase for every refresh eventually locking up the CPU. Probably a leak somewhere

**Comment by martijnjanssen** [comment]
Fixed by #364
