### ISSUE TITLE
Banner is white instead of yellow

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-frontend#306]

**Comment by FrancisBehnen** [comment]
Is this really a bug, or just a wrong css code somewhere?

**Comment by TimvdLippe** [comment]
I suspect it is an issue with the minified code which is not correctly parsed by the css shim. Still need to investigate it, but very low priority imo

**Comment by martijnjanssen** [comment]
Nope, it is not, the exact problem is that the [line](https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-home-page/lancie-image-slider.html#L116) is positioned into the media query, resulting the banner to only have a yellow color under `531px`. A really disappointing issue.
