### ISSUE TITLE
Timetable showing all tabs at once

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#317]
The timetable is broken right now, all the tab content is shown simultaneously. Only one of the days is supposed to show. This is probably an issue with the data binding in the element.

**Comment by FrancisBehnen** [comment]
@MatthijsKok wanted to completely rewrite it right? Adding this to the 2017.2 milestone for now. Create a new rewrite timetable issue and add that to the milestone instead if we still want that.

**Comment by MatthijsKok** [comment]
Timetable needs a complete rewrite yes. I don't think however that the timetable is easily doable for 2017.2

**Comment by martijnjanssen** [comment]
I wouln't rewrite the entire thing, this was the best solution we came up with last year. Styling and placement of the elements is a pain in the ***. So I would advise you to fix the tabs and keep it the same.

**Comment by martijnjanssen** [comment]
Fixed in #416
