### ISSUE TITLE
Change the font-awesome images to iron icon versions

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#336]
Font awesome is great, but not very useful and great to change right now. I can't figure out how to change the color of the svg for some reason and it is sort of redundant to use an image for something that could be solved easier.

**Comment by TimvdLippe** [comment]
I think you can color an svg with a simple `color: yellow`.

**Comment by martijnjanssen** [comment]
Unfortunately, I have tried this, but it does not work.

**Comment by TimvdLippe** [comment]
@martijnjanssen could you elaborate on your previous comment?

**Comment by martijnjanssen** [comment]
The color did not work with the svg, I still don't know why. Fill neither color worked, but I replaced the svg with iron-icons.
