### ISSUE TITLE
Define gulp task to handle deployment to the server

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#339]
E.g. so we can run `npm run build deploy` to optimize images, generate a build and then automatically upload it to the server.

Options:
* https://github.com/spmjs/node-scp2 uses scp which seems like a good option, see http://stackoverflow.com/questions/24639798/how-to-copy-a-folder-over-ssh-with-gulp
* https://github.com/jerrysu/gulp-rsync might be an empty, but requires installing `rsync`.

**Comment by martijnjanssen** [comment]
I would opt for scp over rsync due to the fact that it is simpler and easier to understand for other people.

**Comment by martijnjanssen** [comment]
Closing this in favor of #413.
