### ISSUE TITLE
Refactor dialogs

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#343]
Apparently our dialogs are causing memory leaks, as well as problems with the z-index requiring us to append the dialog to body. We should fix these issues before launching.

**Comment by martijnjanssen** [comment]
Are you sure it is a memory leak? It only takes cpu usage as far as I know.

**Comment by martijnjanssen** [comment]
This was an issue involving the 'vimium' chrome extension. This is also a duplicate of #297 .
