### ISSUE TITLE
Refactor lancie-ticket-block

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-frontend#344]
During the AV, someone suggested for the Early bird tickets to not have a set number, but a time limit instead. After our meeting, we decided that we want that too. I checked throughout our system, and the implementation is already there, except in this element early birds cannot have a deadline. Refactoring this will also help removing the hardcoded tickettypes, and moving to dynamic tickets.

The new code should check if either the deadline, the limit, or both are set, and handle accordingly.

**Comment by martijnjanssen** [comment]
Could you please elaborate on the 'handle accordingly'? I'm looking into implementing this right now :tada:
