### ISSUE TITLE
Check my-area order functionality

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#35]
The Order element of My Area should display all orders. It's very basic, so should be checked and possibily extended.

**Comment by Icety** [comment]
There seem to be orders visible but without any styling, we should add this styling and then this issue seems fixed to me.

**Comment by Icety** [comment]
Done enough for the milestone, it's not done however.

**Comment by skamoen** [comment]
Sort-of-fixed in #40. Closing, see #61 for further steps
