### ISSUE TITLE
Change endpoints for seat requests

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-frontend#351]
Changes in https://github.com/AreaFiftyLAN/lancie-api/pull/332 will break some requests, namely:
- POST /seats/{group}/{number} with param ticketId -> POST /seats/{group}/{number}/{ticketId}
- POST /seats/reservations with SeatReservationDTO body -> POST /seats/{group}/{number}
- GET /users/{userId}/seat -> GET /seats/user/{userId}
- GET /teams/{teamName}/seats -> GET /seats/team/{teamName}

**Comment by martijnjanssen** [comment]
Fixed in #414
