### ISSUE TITLE
Sponsor logos frontpage are not aligned well

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-frontend#37]

**Comment by TimvdLippe** [comment]
This is because the images you provided do not have the same height.

**Comment by drennings** [comment]
Also take into account the alignment of the CH logo. The images should be reshaped to align well automatically, purely a non-programming, but photoshop issue.

**Comment by Icety** [comment]
I thought of this as well, but because the Topicus logo is aligned really bad, fixing it through programming is the only option
