### ISSUE TITLE
LanCie Roles get different sizes on a small screen/ mobile device

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-frontend#38]

**Comment by TimvdLippe** [comment]
Could you attach a screenshot and what you expect? I think this is working as intended to be responsive

**Comment by Icety** [comment]
![image](https://cloud.githubusercontent.com/assets/2795818/13071245/7c2a9a7a-d492-11e5-993e-e28f829ccddd.png)
Misschien is het handiger om ze allemaal onder elkaar te zetten.
