### ISSUE TITLE
Change sponsor display

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#410]
Wrapping of the sponsor images is kinda odd right now. The space the images have to fit in is very small, resulting in only 2 images being displayed on one line. We should rethink the sponsors section on the website, maybe allowing the sponsors to use the full webpage width instead of a mere 800px of it.

Some discussion was done before in #408.

**Comment by FrancisBehnen** [comment]
If it doesn't get an overhaul at least this should be fixed: a163f8983ea7218319ee6cc69f38155624875f00

**Comment by TimvdLippe** [comment]
Seems to be fine for now.
