### ISSUE TITLE
Registration confirmation page

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#45]
We need a dedicated page to put in the email for registration confirmation. It will be called like

`confirm?token=<lalala>`

See AuthenticationController for the type of requests needed. Fairly straightforward

**Comment by martijn9612** [comment]
Is this issue actually fixed now or did you mean something different from the implementation above?

**Comment by TimvdLippe** [comment]
This is fixed in #63
