### ISSUE TITLE
The option for the pickup service shouldn't be available when you are outside the radius

### ISSUE THREAD

**Issue by mpasterkamp** [AreaFiftyLAN/lancie-frontend#459]
As mentioned in the title, when your address is outside the radius you should not be able to take part in the pickup service

**Comment by MatthijsKok** [comment]
Thanks for creating this issue! Since we are so close to this edition and tickets have already been sold, I will assign this to next years ticket sale opening.

**Comment by MatthijsKok** [comment]
I am thinking about a popup warning you when you are outside of the radius, but disallowing this is in my opinion not what we want.

**Comment by TimvdLippe** [comment]
We can probably use the Google Maps API for this: https://developers.google.com/maps/documentation/distance-matrix/start
