### ISSUE TITLE
As a team captain, I can't remove myself from a team

### ISSUE THREAD

**Issue by mpasterkamp** [AreaFiftyLAN/lancie-frontend#466]
I was trying to delete an old team, and thought you can do that by removing everyone. However, as a teamcaptain I can't remove myself from the team

**Comment by martijnjanssen** [comment]
Closing this issue since it is a duplicate of [this issue](https://github.com/AreaFiftyLAN/lancie-frontend/issues/353).

**Comment by MatthijsKok** [comment]
Thanks for opening an issue :)
However, since this is a duplicate of #353, we will be closing this.
