### ISSUE TITLE
Facebook feed element

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#482]
To keep the website up to date and in sync with facebook posts, we want an element that shows the last N elements from the Area FiftyLAN page. This can probably use the facebook api

**Comment by TimvdLippe** [comment]
http://stackoverflow.com/questions/9187419/how-to-embed-a-facebook-pages-feed-into-my-website

**Comment by skamoen** [comment]
Fixed in #539. Well done @DieuwerH!
