### ISSUE TITLE
Change username fields to email

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#488]
The API will start using email instead of username for the main user identifier after [this PR](https://github.com/AreaFiftyLAN/lancie-api/pull/406) is merged.

**Comment by martijnjanssen** [comment]
There is a big change that the password reset is currently broken and `my-area-ticket-item` has several username occurences that have to be changed to email: https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-my-area/my-area-ticket-item.html

**Comment by martijnjanssen** [comment]
Currently, password reset is completely broken since the email field is commented... Welp...

**Comment by skamoen** [comment]
Fixed on all places we encountered it. make specific issues if we missed one
