### ISSUE TITLE
Update Seat taken/locked code to API changes.

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-frontend#492]
https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-seatmap/lancie-seat.html#L90

We use the taken flag here, but that has been deprecated.
We now use a locked flag. This flag has some small differences:
- It is completely independent whether the seat is taken or not.
- It is only modifiable by admins.

**Comment by TimvdLippe** [comment]
I think this has been solved in #593
