### ISSUE TITLE
Replace (fav)icon

### ISSUE THREAD

**Issue by drennings** [AreaFiftyLAN/lancie-frontend#51]
Replace the current [default chrome touch icon](https://areafiftylan.nl/images/touch/chrome-touch-icon-192x192.png) with a space invader [(fav)icon](https://en.wikipedia.org/wiki/Favicon) in:

`<link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon-192x192.png">`

**Comment by TimvdLippe** [comment]
Dupe of #47? Or was it not fixed on master as commented at https://github.com/AreaFiftyLAN/lancie-frontend/issues/47#issuecomment-185896809

**Comment by martijn9612** [comment]
It was indeed fixed, closing this one.
