### ISSUE TITLE
Update website text for 2018

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#528]
The current website content text is heading for its 4th birthday. Time for a rewrite, as the event isn't super new and shiny anymore and certain aspects might have changed. It doesn't have to be the same structure, just focus on selling tickets and informing potential sponsors what the event is all about.

Must fix before first 2018.0 release

**Comment by Fastjur** [comment]
Yes agreed! We'll update it before the save the date goes live!

**Comment by elarb** [comment]
Can this be closed per #538?
