### ISSUE TITLE
Profile updating needs better error handling

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-frontend#54]
I would like to see the editing of the profile data a little different. When pressing save and all went right is perfect right not. When errors occur I would like to still see the error message. Besides that the form should not disappear but should stay, all fields that have an error should color red and show a small message (popup or below/above) showing what went wrong.

**Comment by skamoen** [comment]
Agreed. This would probably result in a separate profile edit element. A lot can be done using client side verification, as implementing every single error in the api is quite tedious and in my opinion not really the api's job.

**Comment by Icety** [comment]
Sadly you always need to check it in the api since a user is able to modify frontside javascript to avoid the checks.

**Comment by Icety** [comment]
Checking it in the frontend before sending would however be perfect!

**Comment by skamoen** [comment]
It is always checked in the api, but in an automated way that doesn't throw a specific error for each erroneous field. That's my point :-)

**Comment by martijn9612** [comment]
Maybe it is a good idea for the api to throw a 400 bad request error with in the request body the names of the fields containing an error?

**Comment by martijn9612** [comment]
Maybe it is a good idea for the api to throw a 400 bad request error with in the request body the names of the fields containing an error?

**Comment by Icety** [comment]
That already happens, yet it should not throw a 400 error, since your browser wont be happy about it.
See https://github.com/AreaFiftyLAN/lancie-api/issues/131

**Comment by skamoen** [comment]
Well, the browser shouldn't be happy about it. Returning a 200 OK while the request didn't do what you would expect it, is even stranger.

**Comment by TimvdLippe** [comment]
@martijnjanssen was this fixed with your error element?

**Comment by martijnjanssen** [comment]
No it was not, I only changed the way the errors are shown.
