### ISSUE TITLE
Page rendering issues when Google Dictionary extension is used on chrome

### ISSUE THREAD

**Issue by Fastjur** [AreaFiftyLAN/lancie-frontend#545]
Steps to reproduce:

* Install [this](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?utm_source=chrome-app-launcher-info-dialog) extension on chrome
* Navigate to https://areafiftylan.nl
* Watch how the page rendering is incorrect

@TimvdLippe Is this polyfill related?

**Comment by TimvdLippe** [comment]
It is probably polyfill related. Will see if someone else knows whats going
on

Op ma 11 dec. 2017 om 17:27 schreef Jurriaan Den Toonder <
notifications@github.com>:

**Comment by Fastjur** [comment]
Alright thank you :+1:

**Comment by skamoen** [comment]
Can you recheck? #571 Might have fixed this one too

**Comment by Fastjur** [comment]
Can confirm the page is now rendering correctly :tada: 

The google dictionary popup shows up on the left top of the screen though, but at least the page renders
