### ISSUE TITLE
No text on Firefox

### ISSUE THREAD

**Issue by Fastjur** [AreaFiftyLAN/lancie-frontend#546]
# Steps to reproduce

* Open https://areafiftylan.nl

# System

* Firefox Quantum - 57.0 (64 bit) for Ubuntu canonical - 1.0

# Screenshot

![image](https://user-images.githubusercontent.com/1493561/33841828-0a689302-de99-11e7-82f1-8593731774e4.png)

**Comment by skamoen** [comment]
Can't reproduce on Firefox 56, 57, 58 (Windows and Arch Linux) with both hardware acceleration disabled or enabled.

**Comment by Fastjur** [comment]
https://support.mozilla.org/en-US/questions/1186663

Closing this as it appears to be more a FF or Ubuntu issue
