### ISSUE TITLE
Change text to justify on homepage

### ISSUE THREAD

**Issue by Fastjur** [AreaFiftyLAN/lancie-frontend#548]
As an experiment, I changed everything to `text-align: justify` where appropriate:

![image](https://user-images.githubusercontent.com/1493561/33848727-e268a53e-deae-11e7-90ea-001932081f54.png)

This makes the page have 'visual lines' at the side of the text, and gives a more readable look to the page IMO.

Any thoughts?

**Comment by TimvdLippe** [comment]
Yeah this seems like a good change.

Op ma 11 dec. 2017 om 20:07 schreef Jurriaan Den Toonder <
notifications@github.com>:

**Comment by TimvdLippe** [comment]
This was fixed in #549
