### ISSUE TITLE
Secondary color leaking to styling of paper elements

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#552]
We are setting the secondary color to our `yellow`, but this causes paper elements to have random yellow colors in firefox. Changing the value of `--secondary-color` in the `index.html` to red makes them all red. We should consider changing the name of the variable.

**Comment by martijnjanssen** [comment]
Fixed by #558

**Comment by martijnjanssen** [comment]
Apparently, this is not as trivial as it looks. There are some strange things going on in the usage of css variables in between browsers.

**Comment by skamoen** [comment]
Partially fixed in #562. Edge 15 will never support this, but it's fixed in Edge 16 which is shipped with the Fall Creators update. This is as good as it's going to get.
