### ISSUE TITLE
Polyfill issue in Edge

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#554]
In Edge, the content doesn't load at all, and throws the following error:

>Object doesn't support property or method 'getElementById'

@elarb Did some research, found that
>"this error usually occurs when an html element id has the same id as some variable in the javascript function"

@martijnjanssen Suggested it's likely somewhere in lancie-ajax and/or lancie-form

**Comment by Fastjur** [comment]
See https://github.com/AreaFiftyLAN/lancie-frontend/pull/521#pullrequestreview-84472145 for some additional information

**Comment by skamoen** [comment]
Fixed in #550
