### ISSUE TITLE
Implement a way to logout

### ISSUE THREAD

**Issue by Fastjur** [AreaFiftyLAN/lancie-frontend#555]

**Comment by martijnjanssen** [comment]
I was thinking of a `paper-icon-button` with the logout sign on it in the header. For mobile we'll also need one in the drawer. But another, better way is also fine 🤔

**Comment by Fastjur** [comment]
I think that is the way to go honestly

**Comment by skamoen** [comment]
Depends on https://github.com/AreaFiftyLAN/lancie-api/pull/455

**Comment by martijnjanssen** [comment]
We're going to implement this by calling the logout endpoint and navigating to a `/logout` route. This logout page will immediately refresh the page/navigate to `/` from javascript. If this refresh action is blocked by an adblocker or something similar, the text on the page will tell the user to refresh or have a navigation link to the homepage.

**Comment by elarb** [comment]
Implemented in #646
