### ISSUE TITLE
Update nginx to return 404 for file requests

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#565]
If a file is requested and it is not found, we should return a 404, not index.html. This means that normal urls fall back to index.html, but anything `*.{js,html,css}` should 404 instead.

I think we should do this by adding a new `location` directive in front of the current one, matching on `location ~* (.html|.js|.css)$` and do `try_files $uri` there

**Comment by skamoen** [comment]
How does this work now that we're using PRPL? https://areafiftylan.nl/doesntexist goes to a 404 now. Can we close this?

**Comment by TimvdLippe** [comment]
URLs are redirected, but files should not. E.g. https://areafiftylan.nl/doesntexist.png should be a plain 404 by Nginx and not show our site

**Comment by TimvdLippe** [comment]
It appears this has been resolved, as clicking on the above link appropriately returns a 404 now. This was probably fixed in the upstream WISVCH proxy?
