### ISSUE TITLE
[CRITICAL] backslash behind tickets URL crashes site

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#566]
The link https://areafiftylan.nl/tickets/ is in the email. It will crash the site. https://areafiftylan.nl/tickets works though.

Happens in both Chrome and Firefox.

![image](https://user-images.githubusercontent.com/6398452/34776287-9afad27e-f616-11e7-91a6-1e825f69e0c6.png)

**Comment by Fastjur** [comment]
Thanks!

We are working at it at the moment! The fix should be rolling out any minute now!
