### ISSUE TITLE
Birthday not editable when empty on mobile

### ISSUE THREAD

**Issue by florisverburg** [AreaFiftyLAN/lancie-frontend#585]
At least on safari on iOS

**Comment by elarb** [comment]
Thanks! I was able to reproduce this on Safari (iOS). Seems to be due to it being possible to make it empty on Safari.

**Comment by skamoen** [comment]
Doesn't work on Chrome on iOS either.

**Comment by elarb** [comment]
Corresponding issue: https://github.com/PolymerElements/paper-input/issues/352

Giving the input element a height seems to be fixing it, e.g.: 

```
 --paper-input-container-input: {
      min-height: 1px;
    };
```
