### ISSUE TITLE
Update Timetable element to show events

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#6]
- [ ] Must show events per day
- [ ] Must be responsive
- [ ] Must initially show the current day

**Comment by TimvdLippe** [comment]
Please post the schedule when it is available for publishing, so we can update this element @bvanderdrift

**Comment by bvanderdrift** [comment]
Sorry, completely missed this. Currently high priority due to this being a requirement by RIOT to be eligible for being an official LoL tournament. See Slack for a link to the tournament planning.

**Comment by bvanderdrift** [comment]
Even though we're not sure all tournaments will be fully filled with teams, please integrate this on the site as-if.
