### ISSUE TITLE
Logos partners really small

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-frontend#604]
On Safari Version 11.0.2  and Google ChromeVersion 64.0.3282.140 the logos of the partners are really small.

![screen shot 2018-02-12 at 11 25 54](https://user-images.githubusercontent.com/5946485/36092431-9d717a9a-0fe7-11e8-91d0-42395576265e.png)

**Comment by skamoen** [comment]
Works on Linux FF 59 and Chrome 64. Likely Apple specific.

**Comment by elarb** [comment]
Possible fixed by #619

**Comment by martijnjanssen** [comment]
@svenpopping could you test this on the beta environment?

**Comment by skamoen** [comment]
Fixed in #619
