### ISSUE TITLE
Properly materialize My Area: Orders & Tickets 

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#61]
It's just functional for now, but it's not as pretty as intended or as the rest of the site. Fix this shit. Soon. ish.

**Comment by TimvdLippe** [comment]
What is the status of this issue?

**Comment by skamoen** [comment]
It's fugly
![image](https://cloud.githubusercontent.com/assets/3198784/13382096/77a69de4-de6c-11e5-8d2f-40f4904c6c20.png)

Still open.
