### ISSUE TITLE
Change Hearthstone tournament title

### ISSUE THREAD

**Issue by MaaikeMol** [AreaFiftyLAN/lancie-frontend#623]
Replace Hearthstone World of Warcraft: Heroes of Warcraft by CampZone World of Warcraft: Heroes of Warcraft.

**Comment by TimvdLippe** [comment]
@MaaikeMol Please open a PR that changes https://github.com/AreaFiftyLAN/lancie-frontend/blob/c48a997f57e3c860ad09c4224c4d6e8fb058afff/data/official-tournaments.json#L50 to the new text.

**Comment by TimvdLippe** [comment]
This has been fixed in #625
