### ISSUE TITLE
Not able to remove self as last member of team

### ISSUE THREAD

**Issue by FlorisXll** [AreaFiftyLAN/lancie-frontend#628]
As a team captain I cannot remove myself from a team where I'm the last member (in MyArea).

It might be that `_canRemove(member, team)` returns false in [Team-Item](https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-my-area/my-area-teams/team-item.html#L153).

The Remove button in the modal does not give me a flash message and holds the display of the modal.

**Comment by martijnjanssen** [comment]
Thanks for the issue, I moved it here: https://github.com/AreaFiftyLAN/lancie-api/issues/484
