### ISSUE TITLE
Request to /logout blocked by CORS policy

### ISSUE THREAD

**Issue by elarb** [AreaFiftyLAN/lancie-frontend#654]
The request to `/logout` on the API is blocked because of the current CORS policy:

![screenshot from 2018-12-25 06-02-50](https://user-images.githubusercontent.com/18485279/50412842-e79c8300-080a-11e9-961c-e133c0caa857.png)

This leads to the `logout` event not getting fired when a user taps on the logout button.

**Comment by DevDonut** [comment]
I don't think this is an issue anymore
