### ISSUE TITLE
Mention SC Events on website

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#69]
Somewhere in the introduction text, we need to mention "In cooperation with SC Events". The Logo doesn't have to be there, though it might be good to add the TUDelft logo as well below the CH logo.

**Comment by martijn9612** [comment]
We will also add the TU-Delft logo since the logo is also on the banner.

**Comment by TimvdLippe** [comment]
Please post the images to be added.

**Comment by skamoen** [comment]
![image](https://cloud.githubusercontent.com/assets/3198784/13441428/5f383aa6-dff7-11e5-8a13-b9427adb4081.png)

"This spectacular all-weekend event, from …., will be organized in cooperation with Unit Sports & Culture, TU Delft."

**Comment by skamoen** [comment]
This is better: https://intranet.tudelft.nl/index.php?eID=tx_nawsecuredl&u=0&file=/fileadmin/secure/UD/ICT/TU_Delft_Intranet_Besloten/Intranet_SC/Huisstijl/Downloads/PNG/S_C_TU_Delft_logo_zwart_geen_URL.png&t=1456955396&hash=21ac906e2de1295e82e8b9046b0a927bcf92dedb

**Comment by bvanderdrift** [comment]
S&C'd like us to use the normal TU Delft logo for anything which externals from the TU will see. This includes the website

![](https://intranet.tudelft.nl/fileadmin/Files/medewerkersportal/mc/huisstijl/Downloads/TU_Delft_logo_RGB.png)

**Comment by bvanderdrift** [comment]
New text (addition of SC cooperation):

> Area FiftyLAN is the hottest gaming event of the TU Delft. This spectacular all-weekend event, from 3 till 5 June 2016, will be organized by the study association of mathematics and computer science 'Christiaan Huygens' in cooperation with Unit Sports & Culture, TU Delft. All students are welcome to bring their PC's or laptops to play their favorite games with their fellow students and friends. You decide what to play! There will be exciting competitive tournaments like Rocket League, CS:GO, Heartstone and League of Legends. If you're not into competitive gaming however, no problem! You can play all the games you want, whether that's The Sims, Age of Empires 2, Rollercoaster Tycoon or Minecraft, you decide!

>That is not all! There will be plenty to do offline as well. Poker and foosball masters can also show off in this event. In the Launch Area, you'll find pinball machines, airhockey tables, football tables and various retro gaming consoles. An overview of things you can do besides gaming can be found below.
