### ISSUE TITLE
Add sponsors to sponsors section

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#7]
Add a list of sponsors with corresponding logos in the sponsors section.

**Comment by TimvdLippe** [comment]
Assigned to @bvanderdrift for the list of sponsors and images of logos

**Comment by bvanderdrift** [comment]
Op dit moment zijn de sponsors nog niet rond. Het gaat om 3 sponsors, wellicht kan je al placeholders gebruiken. Het ziet er naar uit dat het heel bijna af is, dan kunnen de plaatjes aangeleverd worden

**Comment by Icety** [comment]
De sponsors zijn rond, Daan is bezig om geschikte afbeeldingen te krijgen van de sponsors.

**Comment by TimvdLippe** [comment]
Fixed in #17
