### ISSUE TITLE
Create my area

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#8]
**Design**
My area should contain the following information in subpages:

 * Personal information <br>
Show the contens of [the user profile](https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/model/Profile.java)
 * Ticket status <br>
  * If the user bought a ticket, show the details.
  * Else show a form that sends an Order (ref: https://github.com/AreaFiftyLAN/lancie-api/issues/65)

**Comment by TimvdLippe** [comment]
@bvanderdrift please update this ticket will all information once it is set in stone and reassign when it is ready to be implemented.

**Comment by Icety** [comment]
I would just make it one page, creating 2 blocks (cards). The top block contains your personal information (profile) and the block below shows a list of all your tickets. 
You should be able to open and close both blocks.

Personal Information:
I would prefer a profile image and next to it multiple input fields, containing your information. 

Ticket Status:
A table with in its header a button to buy more tickets.
For each bought ticket a row in the table showing the type of ticket and the payment status.
If the payment status is succesful:
If it is redeemed, show by who it is redeemed, if not, show a link to give the ticket away, this link could either link to a separate page or a popup.

**Comment by Icety** [comment]
![image](https://cloud.githubusercontent.com/assets/2795818/12170351/e036cbd6-b540-11e5-874e-59dec00e401f.png)

**Comment by TimvdLippe** [comment]
This thursday, @skamoen and me will work on this feature and it should be finished that afternoon.

**Comment by skamoen** [comment]
Fixed in #40
