### ISSUE TITLE
Set default text if profile is not filled in

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#83]
![image](https://cloud.githubusercontent.com/assets/5948271/13382109/bc318b72-de6c-11e5-943c-ded710c7a0be.png)

Simply text with: "Not yet filled in" would fill all this empty space.

**Comment by martijn9612** [comment]
Wouldn't this break the flow introduced in the profile intercept?

**Comment by skamoen** [comment]
It would be a front-end thing only in my-area. The Profile still wouldn't be set in the back-end, so the intercept shouldn't change.
