### ISSUE TITLE
Review images in slider

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#9]
https://github.com/AreaFiftyLAN/lancie-frontend/commit/724cbe17fa12f47996253576765398eeb59dd27e introduced an image slider. [The current images](https://github.com/AreaFiftyLAN/lancie-frontend/blob/724cbe17fa12f47996253576765398eeb59dd27e/app/elements/lancie-home-page/lancie-image-slider.html#L15-L24) are 3110x2074 pixels.

For performance reasons, it might be better to use smaller images (300x200).

**Comment by bvanderdrift** [comment]
Suggested new images:
https://areafiftylan.nl/photo/gallery-images/IMG_3059.JPG
https://areafiftylan.nl/photo/gallery-images/IMG_3202.JPG
https://areafiftylan.nl/photo/gallery-images/IMG_3344.JPG
https://areafiftylan.nl/photo/gallery-images/IMG_3609.JPG
https://areafiftylan.nl/photo/gallery-images/IMG_3692.JPG

**Comment by bvanderdrift** [comment]
Their scaled-down counterparts:

![img_3059](https://cloud.githubusercontent.com/assets/6398452/12677446/6885d1a8-c699-11e5-9c52-d1c809f4bf03.JPG)
![img_3202](https://cloud.githubusercontent.com/assets/6398452/12677447/6a25e55c-c699-11e5-9329-f650eafaf270.JPG)
![img_3344](https://cloud.githubusercontent.com/assets/6398452/12677449/6bf8c796-c699-11e5-93e5-f4b4fd9df1e9.JPG)
![img_3609](https://cloud.githubusercontent.com/assets/6398452/12677450/6d10fae0-c699-11e5-9bca-cc8d4aeb13c5.JPG)
![img_3692](https://cloud.githubusercontent.com/assets/6398452/12677451/6e04cf94-c699-11e5-8cf4-865140db8026.JPG)
